In [210]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))
    

[1, 1, 2, 3, 6, 8, 10]


In [7]:
x = 3
print(type(x))
print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)

<class 'int'>
3
4
2
6
9


In [135]:
x = 3
x += 1
print(x)
x *= 2
print(x)

4
8


In [139]:
y = 2.5 
print(type(y))
print(y,y+1,y*2,y**2)

<class 'float'>
2.5 3.5 5.0 6.25


In [140]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)

<class 'bool'>
False
True
False


In [147]:
hello = 'hello'
world = 'world'
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


# String object have a bunch of useful methods; for example:

In [151]:
s = 'hello'
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l','(ell)'))
print('  world   '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [155]:
xs = [3,1,2]
print(xs,xs[2],xs[-1])
xs[2]='foo'
print(xs)
xs.append('bar')
print(xs)
x = xs.pop()
print(x, xs)

[3, 1, 2] 2 2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [158]:
num = list(range(5))
print(num)
print(num[2:4])
print(num[2:])
print(num[:2])
print(num[:])
print(num[:-1])
num[2:4] = [8,9]
print(num)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


Loops: you can look over the elements of a lists:

In [160]:
animals = ['cat','dog','monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [163]:
animals = ['cat','dog',"monkey"]
for idx,animal in enumerate(animals):
    print('#%d %s' %(idx +1, animal))
#syntax is in side the quotes %d or %s

#1 cat
#2 dog
#3 monkey


In [166]:
# list comprehension
nums = [0,1,2,3,4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [169]:
squares = [x**2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


In [173]:
d = {'cat':'cute','dog':'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d)
print(d.get('monkey','N/A'))
print(d.get('fish','N/A'))
del d['fish']
print(d.get('fish','N/A'))

cute
True
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}
N/A
wet
N/A


In [174]:
d = {'person':2,'cat':4,'spider':8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' %(animal,legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [175]:
d = {'person':2,'cat':4, 'spider':8}
for animal,legs in d.items():
    print('A %s has %d legs' %(animal,legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [176]:
nums = [0,1,2,3,4]
even_num_to_square = {x:x**2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [179]:
print([i for i in enumerate(d)])

[(0, 'person'), (1, 'cat'), (2, 'spider')]


In [187]:
#set
animals = {'cat','dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(animals)

True
False
True
3
3
{'fish', 'dog'}


In [208]:
animals = {'cat','dog','fish'}
for idx,animal in enumerate(animals):
    print('#%d %s' %(idx+1,animal))

#1 cat
#2 fish
#3 dog


In [212]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


In [217]:
#tuple : can be used as key of a dictionary
d = {(x,x+1): x for x in range(10)}
t = (5,6)
print(type(t))
print(d)
print(d[t])
print(d[(1,2)])

<class 'tuple'>
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


Functions

In [218]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1,0,1]:
    print(sign(x))

negative
zero
positive


In [220]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('hello, %s' %name)
hello('bob')
hello('fred',loud = True)

hello, bob
HELLO, FRED!


In [227]:
class Greeter(object):
    #Constructor
    def __init__(self,name):
        self.name = name #create a instance variable
    def greet(self, loud = False):
        if loud:
            print('HELLO %s'% self.name.upper())
        else:
            print('hello %s'% self.name)

g = Greeter('fred')
g.greet()
g.greet(loud = True)

hello fred
HELLO FRED


In [232]:
import numpy as np 

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[0,2])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 3


In [244]:
import numpy as np 

a = np.zeros((2,2))
print(a)

a = np.ones((1,2))
print(a)

a = np.full((2,2),7)
print(a)

a = np.eye(2)
print(a)

a = np.random.random((3,2,3))
print(a)
print(a[1,1,])

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[7 7]
 [7 7]]
[[ 1.  0.]
 [ 0.  1.]]
[[[ 0.7899914   0.30341091  0.77423189]
  [ 0.0218812   0.82242658  0.79692554]]

 [[ 0.86415264  0.51884694  0.40532241]
  [ 0.35142546  0.54680002  0.41021702]]

 [[ 0.84121325  0.67728989  0.28439236]
  [ 0.53077061  0.20570598  0.75707118]]]
[ 0.35142546  0.54680002  0.41021702]


In [250]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

#first row, than column
print(a[:2,1:3])

b = a[:2,1:3]

print(a[0,1])

b[0,0] = 77
print(a[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [254]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

col_c1 = a[:,1]
col_c2 = a[:,1:2]
print(col_c1,col_c1.shape)
print(col_c2,col_c2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [266]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[2 2]
[2 2]
